---

name: Time DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Short SHA
      run: |
        echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c 1-7)" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t time-devops-project/mikeproject:${{ env.SHORT_SHA }} .
    
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push DockerHub
      run: |
        docker push time-devops-project/mikeproject:${{ env.SHORT_SHA }}

    
